version: '3.1'

services:
  db:
    image: mysql:8.0.25
    container_name: db
    restart: always
    secrets:
      - mysql_root
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root
      MYSQL_DATABASE: donuts
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    network_mode: "host"

  voyager_donuts:
    container_name: voyager_donuts
    build:
      context: .
      dockerfile: Dockerfile
    image: voyager_donuts
    network_mode: "host"
    volumes:
      - c:/Users/itelescope/Dropbox/MoanaSSO/DonutsCalibration:/voyager_calibration
      - c:/Users/itelescope/Dropbox/MoanaSSO/DonutsLog:/voyager_log
      - c:/Users/itelescope/Dropbox/MoanaSSO:/voyager_data
      - c:/Users/itelescope/Dropbox/MoanaSSO/DonutsReference:/voyager_reference

volumes:
  mysql-data:

secrets:
  mysql_root:
    file: ./secrets/mysql_root
